# Generated by Django 4.0.4 on 2022-05-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
